### PR TITLE
Resolve Wallet Encryption Vulnerability, Fix BLOK-32

### LINKED ISSUE #680: VULNERABILITY: Backup shards are being signed and not encrypted, making vault insecure
https://github.com/sonr-io/sonr/blob/ee074bb1d746ce064d2a2f4cfe4f51a7e1549a25/pkg/crypto/mpc/wallet.go#L228

ECDSA cannot be used for encryption, so another system needs to be devised to securely encrypt these shards.

### PR DESCRIPTION
**Pull request by mcjcloud**
Replaces wallet signing of vault shards with encryption using PSK. The PSK works as a good encryption key because it
1. is a symmetric key that can be used for encryption and decryption
2. is always required to create an account/sign in
3. is shared between all devices, so no need to keep track of multiple encryption keys

## Changes
- Replace shard signing with encryption
- Add a new `encryptionKey` property to `motorNodeImpl`

Fixes #680 

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by prnk28** [comment]
https://linear.app/sonr-io/issue/BLOK-32/vulnerability-backup-shards-are-being-signed-and-not-encrypted-making

**Comment by prnk28** [comment]
https://linear.app/sonr-io/team/BLOK/new?title=VULNERABILITY%3A%20Backup%20shards%20are%20being%20signed%20and%20not%20encrypted%2C%20making%20vault%20insecure&description=%5Bhttps%3A%2F%2Fgithub.com%2Fsonr-io%2Fsonr%2Fblob%2Fee074bb1d746ce064d2a2f4cfe4f51a7e1549a25%2Fpkg%2Fcrypto%2Fmpc%2Fwallet.go%23L228%5D(https%3A%2F%2Fgithub.com%2Fsonr-io%2Fsonr%2Fblob%2Fee074bb1d746ce064d2a2f4cfe4f51a7e1549a25%2Fpkg%2Fcrypto%2Fmpc%2Fwallet.go%23L228)%0A%0AECDSA%20cannot%20be%20used%20for%20encryption%2C%20so%20another%20system%20needs%20to%20be%20devised%20to%20securely%20encrypt%20these%20shards.&assignee=brayden&priority=2&status=In%20Progress&cycle=Cycle%202&project=Authorization%2C%20MPC%2C%20and%20Registry%20Module&labels=Bug

**Comment by prdlk** [comment]
@mcjcloud Next time lets use the branch provided by linear `brayden/blok-32`

**Review by prdlk — APPROVED** [review]

File: pkg/motor/create_account.go [hunk 1]
```diff
@@ -98,13 +100,13 @@ func (mtr *motorNodeImpl) CreateAccountWithKeys(request mt.CreateAccountWithKeys
 	}
 
 	// encrypt dscShard with DSC
-	dscShard, err := dscEncrypt(mtr.deviceShard, request.AesDscKey)
+	dscShard, err := mpc.AesEncryptWithKey(request.AesDscKey, mtr.deviceShard)
```
Comment (joshLong145) [inline pkg/motor/create_account.go:103]: Did we reimplement `mpc.AesEncryptWithKey` or do we not need to?

Comment (mcjcloud) [reply pkg/motor/create_account.go:103]: No we don't need to. The `dscEncrypt` function was just redundant I realized.

File: pkg/motor/motor_test.go [hunk 2]
```diff
@@ -1,47 +1,17 @@
...
+func (suite *MotorTestSuite) Test_DecodeTxData() {
 	data := "0A91010A242F736F6E72696F2E736F6E722E72656769737472792E4D736743726561746557686F497312691267122A736E723134373071366D3476776D6537346A376D3573326364773939357A35796E6B747A726D377A35371A31122F6469643A736E723A3134373071366D3476776D6537346A376D3573326364773939357A35796E6B747A726D377A353730BC8FA197063801"
 
 	mcr := &rt.MsgCreateWhoIsResponse{}
 	err := client.DecodeTxResponseData(data, mcr)
-	assert.NoError(t, err, "decodes tx data successfully")
-	assert.Equal(t, "snr1470q6m4vwme74j7m5s2cdw995z5ynktzrm7z57", mcr.WhoIs.Owner)
-}
-
-func Test_GetAddress(t *testing.T) {
```
Comment (ntindle) [inline pkg/motor/motor_test.go:28]: Just want to check we want to remove this test case

Comment (mcjcloud) [reply pkg/motor/motor_test.go:28]: It was using the old test system. With the new system there's not really anything to compare the wallet address to.

**Review by joshLong145 — APPROVED** [review]
