### PR TITLE
Ref/schema def on chain

### LINKED ISSUE #556: Refactor Schemas to be on chain
#### Describe the bug

Right now we are storing Schemas

### PR DESCRIPTION
**Pull request by joshLong145**
Removal of `IPFS` storage for SchemaDefinitions
All Schema data is now stored in the same transaction hash within the`WhatIs`

## Changes
- removal of `SchemaReferrence` from `WhatIs` proto definition
- Referencing of `SchemaDefinition` in `WhatIs`
- Removal of motor `IPFS` retrievals for `SchemaDefinitions` instead stores definition in cache from `WhatIs`
- Left motor request objects referencing `SchemaDefinition` in place as convince

## API Updates
-- `SchemainternalImpl` now takes an instance of `client` to query the chain for schemas linked to other schemas. 
- store is now exposed for unit testing purposes of pre hydrating the store to not require chain calls.
## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Resolves #556 

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

File: pkg/motor/query.go [hunk 1]
```diff
@@ -56,11 +56,11 @@ func (mtr *motorNodeImpl) QueryWhatIsByCreator(req mt.QueryWhatIsByCreatorReques
 	// store reference to schema
 	schemas := make(map[string]*st.SchemaDefinition)
 	for _, w := range resp {
-		s, err := mtr.Resources.StoreWhatIs(w)
+		def := w.Schema
```
Comment (mcjcloud) [inline pkg/motor/query.go:59]: nit: Seems like the `def` variable isn't very useful at this point

**Review by mcjcloud — APPROVED** [review]
This looks so much cleaner 🔥

**Review by prdlk — APPROVED** [review]
LFG Josh much better 🔥🔥
