### PR TITLE
Integrate/adr 001

### LINKED ISSUE #259: Fixing up session stuff that's broken
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202534424452609) by [Unito](https://www.unito.io)

### LINKED ISSUE #272: Fix sonr build pipeline and testing
Verify

* [x] Build of protos
* [x] Build of Chain
* [x] Build highway
* [x] Build docs
* [x] Build Motor iOS
* [x] Build Motor Android
* [ ] Build Motor Wasm
* [ ] Build the dashboard
* [ ] Build of wallet
* [ ] Build of dockerfiles

Test

* [ ] protos
* [ ] Chain
* [ ] highway
* [ ] docs
* [ ] dashboard
* [ ] wallet

Deploy

* [ ] dockerfiles
* [ ] sonrd
* [ ] highwayd

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202534239710263) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by prdlk**
# Changes

## New Artifacts

* `motor-wasm` - Utilizes webrtc-direct transport on the host implementation
* `highwayd` - Standalone server for highway

## Structure

* Move `host` into `pkg`, allowing easier cross-module import for internal node implementations *(motor, highway)*
* Move `Callback` into `motor-lib` to bind natively to host operating system
* Restructure monorepo to allow **ignite-cli** methods to be utilized for **cosmos-sdk**:
  * Move `internal/blockchain/app` ➡️ `app/*`
  * Move `internal/blockchain/proto` ➡️ `proto/*`
  * Move `internal/blockchain/scripts/setup_chain_dev.sh` ➡️ `scripts/setup_chain_dev.sh`
  * Move `internal/blockchain/testutil` ➡️ `testutil/*`
  * Move `internal/blockchain/x` ➡️ `x/*`

### `pkg/did`

* Blockchain no longer handles DID Document construction.
* Highway creates DIDDocument using the utility and passes to the blockchain. Then, the blockchain verifies the document is valid with the accompanying owner
* Added utility to insert webauthn credentials into DIDDocument
* Added utility to verify a JWT and read its properties

### `internal/highway`

* Removed gRPC/protobuf definitions for highway
* The blockchain already provides protobuf definitions for when we would utilize client stubs.
* Logically makes most sense for us to operate using HTTP methods and use cosmos client

### `internal/motor`

* Motor-lib directory has build flag for WASM module
* Discovery, Exchange, and Transmission protocols now utilize event emitter to abstract away from Motor Callback

# API Updates

### New Features *(required)*

* All CUD methods now utilize a `JWT` byte array attached with the message. The blockchain verifies ownership utilizing the `JWT` and Document `verificationMethod` `JWK` on every api call.

### Deprecations *(required)*

* `Session` object has been removed from every transaction in favor of `JWT` verification
* Removed `RegisterName()`
* Removed `RegisterApp()`
* Removed `UpdateName()`
* Removed `UpdateApp()`
* Removed `DeleteWhoIs()`

### Enhancements

Updated Registry Spec in order to comply with ADR-001 method handling. Registering a .snr/ name for a specific DIDDocument is now handled independently from the initial DIDDocument generation. This allows us to issue root level DIDDocuments without a .snr/ name being present.

**Create WhoIs Entry**

```
(POST): /v1/registry/create/whois
- Owner:string
- DidDocument:[]byte
- WhoisType:Enum{ WhoisType_APP | WhoisType_USER }
```

This method takes a DIDDocument as an input along with the did of the account calling the TX, and verifies the signature. If succesful, and there is no existing WhoIs created for the user or application. Paramaters include: signature, diddocument, address, and whoIsType.

**Update WhoIs Entry**

```
(POST): /v1/registry/update/whois
- Owner:string
- DidDocument:[]byte
- Did:string
```

This method takes an updated DIDDocument as a JSON buffer along with the signature of the current tx creator, and then verifies the account calling the TX is a controller of the On-chain DIDDocument. If so, the DIDDocument is updated on the blockchain and the transaction is broadcast.

**Deactivate WhoIs Entry**

```
(POST): /v1/registry/deactivate/whois
- Owner:string
- Did:string
```

This method sets the state of a particular WhoIs to be deactivated. In order to successfully perform this request, the TX creator and signature must be the same as the WhoIs owner.

**Buy an Alias for a User**

```
(POST): /v1/registry/buy/alias/name
- Creator:string
- Did:string
- Amount:int32
- Name:string
```

This method purchases a user alias .snr domain i.e. `{example}.snr`, and inserts it into the `alsoKnownAs` field of the app's DIDDocument. Request fails when the DIDDoc type doesnt match, wallet balance is too low, the alias has already been purchased, creator is not listed as controller of DIDDoc, or WhoIs is deactivated.

**Buy an Alias for a Application**

```
(POST): /v1/registry/buy/alias/app
- Creator:string
- Did:string
- Amount:int32
- Name:string
```

This method purchases an app name extension i.e. `example.snr/{appname}`, and inserts it into the `alsoKnownAs` field of the app's DIDDocument. Request fails when the DIDDoc type doesnt match, wallet balance is too low, the alias has already been purchased, creator is not the owner of the app, or WhoIs is deactivated.

**Transfer an Alias for a User**

```
(POST): /v1/registry/transfer/alias/name
- Creator:string
- Did:string
- Alias:string
- Recipient:string
```

This method transfers an existing User .snr name Alias to the specified peer. The alias is removed from the current App's `alsoKnownAs` list and inserted into the new App's `alsoKnownAs` list.

**Transfer an Alias for a Application**

```
(POST): /v1/registry/transfer/alias/app
- Creator:string
- Did:string
- Alias:string
- Recipient:string
```

This method transfers an existing App Alias to the specified peer. The alias is removed from the current App's `alsoKnownAs` list and inserted into the new App's `alsoKnownAs` list.

### Deprecations

The following methods have been refactored in order to ensure developer clarity.

<table><tbody><tr><th colspan="1" rowspan="1"><p><strong>Method</strong></p></th><th colspan="1" rowspan="1"><p><em>Previous Route</em></p></th><th colspan="1" rowspan="1"><p><strong>New Route</strong></p></th></tr><tr><td colspan="1" rowspan="1"><p><strong>GET</strong></p></td><td colspan="1" rowspan="1"><p><code class="proseCode">/v1/name/register/start/:username</code></p></td><td colspan="1" rowspan="1"><p><code class="proseCode">/v1/auth/register/start/:username</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><strong>POST</strong></p></td><td colspan="1" rowspan="1"><p><code class="proseCode">/v1/name/register/finish/:username</code></p></td><td colspan="1" rowspan="1"><p><code class="proseCode">/v1/auth/register/finish/:username</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><strong>GET</strong></p></td><td colspan="1" rowspan="1"><p><code class="proseCode">/v1/name/access/start/:username</code></p></td><td colspan="1" rowspan="1"><p><code class="proseCode">/v1/auth/access/start/:username</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><strong>POST</strong></p></td><td colspan="1" rowspan="1"><p><code class="proseCode">/v1/name/access/finish/:username</code></p></td><td colspan="1" rowspan="1"><p><code class="proseCode">/v1/auth/access/finish/:username</code></p></td></tr></tbody></table>

### Enhancements

* `DIDDocument` is now constructed in the Highway and passed as a JSON buffer to the highway within either the `CreateWhoIs()` or `UpdateWhoIs()` methods.
* Updated Swagger definition for all new methods.

# Checklist

* [ ] Unit tests
* [x] Documentation

# References *(optional)*

Fixes #259, Fixes #272
Connects

 Mention [stepsize] in a comment if you'd like to report some technical debt. See examples here.

### CODE REVIEW

**Comment by mcjcloud** [comment]
Highway API endpoints can be refactored. 
`/v1/registry/create/whois` doesn't separate areas well. Something like `/v1/registry/whois/create` would be better so you can have:

`/v1/registry/whois/create`
`/v1/registry/whois/update`
etc..

Consider all other endpoints.

**Comment by joshLong145** [comment]
Currently the highway cli does not load env variables which prevents standup of the http server, and subsequent modules loaded in "HighwayServer"

**Comment by ntindle** [comment]
Needs Webauthn PR and a transfer alias PR to finish the feature

**Comment by joshLong145** [comment]
Can be observed that the "UnmarshelDidDocument" method on the did type within the "registry" keeper is attempting to unmarshal a document instance that is always "nil" as the created document does not appear to be referenced to the whoIs instance the method is being called from
found in "who_is.go" line 38

File: internal/highway/http/crud_bucket.go [hunk 1]
```diff
@@ -0,0 +1,105 @@
+package core
```
Comment (drgomesp) [inline internal/highway/http/crud_bucket.go]: The package here should be `http` according to the directory structure.

File: internal/highway/highway.go [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+	}
+
+	// Create the Highway Server
+	s, err := core.CreateStub(ctx, c)
+	if err != nil {
+		return nil, err
+	}
+
+	// Register Cosmos HTTP Routes - Registry
+	s.Router.POST("/v1/registry/buy/alias", s.BuyAlias)
```
Comment (mcjcloud) [inline internal/highway/highway.go]: These routes don't seem ordered properly. Instead of `/buy/alias`, consider `/alias/buy`. Same for sell and transfer, and whois endpoints.

File: cmd/highway-cli/highwaycmd/auth.go [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+	}
+	cobra.CheckErr(err)
+
+	select {
+	case <-ctx.Done():
+		fmt.Println("failed.")
+	case c := <-sessChan:
+		fmt.Println("done.")
+		fmt.Print("Saving session... ")
+		fmt.Println(c.ID)
```
Comment (mcjcloud) [inline cmd/highway-cli/highwaycmd/auth.go]: The session isn't actually being saved anywhere here.

File: cmd/highway-cli/main.go [hunk 4]
```diff
@@ -26,6 +36,10 @@ func loadEnv() error {
...
 
 func main() {
-	cobra.CheckErr(loadEnv())
-	cobra.CheckErr(cmd.Execute())
+	logger.Info("Starting highway-cli, loading env variables")
+	err := loadEnv()
+	if err != nil {
+		logger.Errorf("Error while loading enviorment variables: %s", err)
+	}
+	cobra.CheckErr(highwaycmd.Execute())
```
Comment (mcjcloud) [inline cmd/highway-cli/main.go:41]: Why make this change? If loadEnv fails, starting the highway will certainly fail.

File: cmd/highwayd/index.html [hunk 5]
```diff
@@ -0,0 +1,170 @@
+<!DOCTYPE html>
```
Comment (mcjcloud) [inline cmd/highwayd/index.html]: If this is a demo of webauthn I suggest it be moved to a `/demo` folder. Putting it at the root of highwayd makes it seem more related to that than it is.

File: cmd/highwayd/main.go [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+func main() {
+	// Start the app
+	hw, err := highway.NewHighway(context.Background())
+	if err != nil {
+		panic(err)
+	}
+	r := mux.NewRouter()
+
+	r.HandleFunc("/register/begin/{username}", hw.StartRegisterName).Methods("GET")
+	r.HandleFunc("/register/finish/{username}", hw.FinishRegisterName).Methods("POST")
```
Comment (mcjcloud) [inline cmd/highwayd/main.go]: Is register still relevant now that we have CreateWhois and BuyAlias? If so, these routes should go with the others in `highway/http/server.go`

File: cmd/highwayd/main.go [hunk 7]
```diff
@@ -0,0 +1,30 @@
...
+	r.HandleFunc("/login/begin/{username}", hw.StartAccessName).Methods("GET")
+	r.HandleFunc("/login/finish/{username}", hw.FinishAccessName).Methods("POST")
+
+	r.PathPrefix("/").Handler(http.FileServer(http.Dir("./cmd/highwayd/")))
```
Comment (mcjcloud) [inline cmd/highwayd/main.go]: We should serve a static folder here. You can technically hit `http://localhost:8081/main.go` and it will give you the source code since it's in the same directory.

Not a huge problem since we're open source, but having a `static` folder will be safer and cleaner.

File: cmd/highwayd/main.go [hunk 8]
```diff
@@ -0,0 +1,30 @@
...
+
+	serverAddress := ":8081"
```
Comment (mcjcloud) [inline cmd/highwayd/main.go]: Use env variable

File: cmd/motor-lib/bind.go [hunk 9]
```diff
@@ -1,16 +1,22 @@
-package sonr
+package motor
 
 import (
 	//"github.com/kataras/golog"
```
Comment (mcjcloud) [inline cmd/motor-lib/bind.go]: Remove comments

File: cmd/motor-lib/bind.go [hunk 10]
```diff
@@ -1,16 +1,22 @@
...
 	// "google.golang.org/protobuf/proto"
-	_ "golang.org/x/mobile/bind"	
+
+	_ "golang.org/x/mobile/bind"
 )
 
 // Start starts the host, node, and rpc service.
 func Start(reqBuf []byte) {
-
+	//config := config.DefaultConfig(config.Role_MOTOR)
```
Comment (mcjcloud) [inline cmd/motor-lib/bind.go:9]: Looks like this entire method is commented out. Can it be removed?

File: cmd/motor-lib/wasm.go [hunk 11]
```diff
@@ -0,0 +1,24 @@
+//go:build wasm
```
Comment (mcjcloud) [inline cmd/motor-lib/wasm.go]: What exactly is being done in this file? Looks like the WasmHost isn't actually being used. Also this is in the `/cmd` folder, making it look like its own program.

File: cmd/sonrd/didutil/cmd.go [hunk 12]
```diff
@@ -0,0 +1,62 @@
...
+}
+
+// AccAddress returns a sample account address
+func genAccAddressDid() string {
+	pk := ed25519.GenPrivKey().PubKey()
+	addr := pk.Address()
+	addrStr := sdk.AccAddress(addr).String()
+	addrStr = strings.TrimLeft(addrStr, "snr")
+	addrStr = strings.TrimRight(addrStr, "cosmos")
+	return fmt.Sprintf("did:snr:%s", addrStr)
```
Comment (mcjcloud) [inline cmd/sonrd/didutil/cmd.go]: Don't we have DID creation utilities for this? I think creating and manipulating Sonr DIDs can/should be done in the did pkg.

File: cmd/sonrd/didutil/existing_did.go [hunk 13]
```diff
@@ -0,0 +1,169 @@
...
+	"github.com/cosmos/cosmos-sdk/crypto/keys/secp256k1"
+	"github.com/sonr-io/sonr/pkg/did"
+	"github.com/sonr-io/sonr/pkg/did/ssi"
+	"github.com/sonr-io/sonr/x/object/types"
+)
+
+func surveyExistingDid() error {
+	file := ""
+	prompt := &survey.Input{
+		Message: "Enter the path to your DID Json file:",
```
Comment (mcjcloud) [inline cmd/sonrd/didutil/existing_did.go]: It looks like a user of sonrd will have to write out a DID document in a JSON file in order to create it through the CLI.

A better user experience might just be to prompt for the relevant data and generate the rest of it for them. Is there a reason for having them write out the whole struct?

File: cmd/sonrd/didutil/existing_did.go [hunk 14]
```diff
@@ -0,0 +1,169 @@
...
+	// Handle opt
+	switch opt {
+	case "Add Assertion Method":
+		// Add Assertion Method
+		controller := fmt.Sprintf("%s#test-%d", doc.ID, len(doc.Controller))
+		didController, err := did.ParseDID(controller)
+		if err != nil {
+			return err
+		}
+		priv := secp256k1.GenPrivKey()
```
Comment (mcjcloud) [inline cmd/sonrd/didutil/existing_did.go]: The private key needs to be saved somewhere on the hardware if it's to be used for verification later.

File: cmd/sonrd/didutil/existing_did.go [hunk 15]
```diff
@@ -0,0 +1,169 @@
...
+		pub := priv.PubKey()
+		vm, _ := did.NewVerificationMethod(doc.ID, ssi.ECDSASECP256K1VerificationKey2019, *didController, pub)
```
Comment (mcjcloud) [inline cmd/sonrd/didutil/existing_did.go]: Don't ignore error

`cobra.CheckErr(err)`

File: cmd/sonrd/didutil/existing_did.go [hunk 16]
```diff
@@ -0,0 +1,169 @@
...
+	}
+
+	// perform the questions
+	survey.AskOne(selectOpt, &opt, nil)
+
+	// Handle opt
+	switch opt {
+	case "Add Assertion Method":
+		// Add Assertion Method
+		controller := fmt.Sprintf("%s#test-%d", doc.ID, len(doc.Controller))
```
Comment (mcjcloud) [inline cmd/sonrd/didutil/existing_did.go]: `test` should have a better name.

Also, no DID Document is created for the controller, nor is the controller persisted anywhere.

File: cmd/sonrd/didutil/cmd.go [hunk 17]
```diff
@@ -0,0 +1,62 @@
+package didutil
```
Comment (mcjcloud) [inline cmd/sonrd/didutil/cmd.go]: Is didutil just used for testing purposes? If so it should be disabled in production environment. If not, we shouldn't use `CreateMockCredential()`

File: cmd/sonrd/didutil/existing_did.go [hunk 18]
```diff
@@ -0,0 +1,169 @@
...
+		didController, err := did.ParseDID(controller)
+		if err != nil {
+			return err
+		}
+		priv := secp256k1.GenPrivKey()
+		pub := priv.PubKey()
+		vm, _ := did.NewVerificationMethod(doc.ID, ssi.ECDSASECP256K1VerificationKey2019, *didController, pub)
+		vm.Credential = CreateMockCredential()
+		doc.AddAssertionMethod(vm)
+	case "Add Invocation Method":
```
Comment (mcjcloud) [inline cmd/sonrd/didutil/existing_did.go]: The above comments apply to the other couple cases as well.

File: cmd/sonrd/didutil/new_did.go [hunk 19]
```diff
@@ -0,0 +1,112 @@
...
+func surveyNewDid() error {
+	// Webauthn confirmation
+	webauthn := false
+	prompt := &survey.Confirm{
+		Message: "Would you like to generate a Webauthn Credential in your browser?",
+	}
+	survey.AskOne(prompt, &webauthn)
+
+	if webauthn {
+		// Open browser and serve index.html
```
Comment (mcjcloud) [inline cmd/sonrd/didutil/new_did.go]: Incomplete?

File: cmd/sonrd/didutil/new_did.go [hunk 20]
```diff
@@ -0,0 +1,112 @@
...
+			return err
+		}
+
+		// Switch on pubKey
+		switch pubKey {
+		case "EcdsaSecp256k1VerificationKey2019":
+			// Generate EcdsaSecp256k1VerificationKey2019
+			priv := secp256k1.GenPrivKey()
+			pub := priv.PubKey()
+			vm, _ = did.NewVerificationMethod(*didRoot, ssi.ECDSASECP256K1VerificationKey2019, *didController, pub)
```
Comment (mcjcloud) [inline cmd/sonrd/didutil/new_did.go]: Don't ignore error (also apply to other cases)

File: cmd/sonrd/didutil/new_did.go [hunk 21]
```diff
@@ -0,0 +1,112 @@
...
+			Message: "Would you like to save the JSON output to disk?",
+		}
+		survey.AskOne(prompt, &saveFile)
+
+		if saveFile {
+			path := filepath.Join("testutil", "sample", "did.json")
+			ioutil.WriteFile(path, buf, 0644)
+			fmt.Printf("Saved DID JSON Document to: %s\n", path)
+		} else {
+			fmt.Println(string(buf))
```
Comment (mcjcloud) [inline cmd/sonrd/didutil/new_did.go]: Consider printing this out even if `saveFile` is true.

File: cmd/sonrd/genaccounts.go [hunk 22]
```diff
@@ -0,0 +1,184 @@
...
+			serverCtx := server.GetServerContextFromCmd(cmd)
+			config := serverCtx.Config
+
+			config.SetRoot(clientCtx.HomeDir)
+
+			var kr keyring.Keyring
+			addr, err := sdk.AccAddressFromBech32(args[0])
+			if err != nil {
+				inBuf := bufio.NewReader(cmd.InOrStdin())
+				keyringBackend, _ := cmd.Flags().GetString(flags.FlagKeyringBackend)
```
Comment (mcjcloud) [inline cmd/sonrd/genaccounts.go]: Don't ignore error

File: cmd/sonrd/genaccounts.go [hunk 23]
```diff
@@ -0,0 +1,184 @@
...
+		Long: `Add a genesis account to genesis.json. The provided account must specify
+the account address or key name and a list of initial coins. If a key name is given,
+the address will be looked up in the local Keybase. The list of initial tokens must
+contain valid denominations. Accounts may optionally be supplied with vesting parameters.
+`,
+		Args: cobra.ExactArgs(2),
+		RunE: func(cmd *cobra.Command, args []string) error {
+			clientCtx := client.GetClientContextFromCmd(cmd)
+			depCdc := clientCtx.Codec
+			cdc := depCdc.(codec.Codec)
```
Comment (mcjcloud) [inline cmd/sonrd/genaccounts.go]: If the cmd context isn't set, this will error. Add `ok` check

File: cmd/sonrd/genaccounts.go [hunk 24]
```diff
@@ -0,0 +1,184 @@
...
+
+			serverCtx := server.GetServerContextFromCmd(cmd)
```
Comment (mcjcloud) [inline cmd/sonrd/genaccounts.go:51]: Is this guaranteed not to be nil?

File: cmd/sonrd/genaccounts.go [hunk 25]
```diff
@@ -0,0 +1,184 @@
...
+			}
+
+			coins, err := sdk.ParseCoinsNormalized(args[1])
+			if err != nil {
+				return fmt.Errorf("failed to parse coins: %w", err)
+			}
+
+			vestingStart, _ := cmd.Flags().GetInt64(flagVestingStart)
+			vestingEnd, _ := cmd.Flags().GetInt64(flagVestingEnd)
+			vestingAmtStr, _ := cmd.Flags().GetString(flagVestingAmt)
```
Comment (mcjcloud) [inline cmd/sonrd/genaccounts.go]: Don't ignore errors

File: cmd/sonrd/genaccounts.go [hunk 26]
```diff
@@ -0,0 +1,184 @@
...
+)
+
+const (
+	flagVestingStart = "vesting-start-time"
+	flagVestingEnd   = "vesting-end-time"
+	flagVestingAmt   = "vesting-amount"
+)
+
+// AddGenesisAccountCmd returns add-genesis-account cobra Command.
+func AddGenesisAccountCmd(defaultNodeHome string) *cobra.Command {
```
Comment (mcjcloud) [inline cmd/sonrd/genaccounts.go:33]: This method is very long, consider breaking up some of the functionality into helper functions.

File: internal/highway/http/crud_bucket.go [hunk 27]
```diff
@@ -0,0 +1,105 @@
...
+// @Success      200  {object}  bt.MsgCreateBucketResponse
+// @Failure      500  {string}  message
+// @Router /v1/bucket/create [post]
+func (s *HighwayServer) CreateBucket(c *gin.Context) {
+	// Unmarshal the request body
+	var req bt.MsgCreateBucket
+	if err := c.ShouldBindJSON(&req); err != nil {
+		c.JSON(http.StatusBadRequest, gin.H{
+			"error": t.ErrRequestBody.Error(),
+		})
```
Comment (mcjcloud) [inline internal/highway/http/crud_bucket.go]: Add `return` after this. Otherwise you'll end up trying to send a response multiple times.

I noticed this is happening in multiple places so make sure every response is followed by `return` so the method doesn't keep executing.

File: internal/highway/http/crud_channel.go [hunk 28]
```diff
@@ -0,0 +1,169 @@
...
+	}
+
+	// Return the response
+	c.JSON(http.StatusOK, gin.H{
+		"code":    resp.Code,
+		"message": resp.Message,
+	})
+}
+
+// // @Summary Listen Channel
```
Comment (mcjcloud) [inline internal/highway/http/crud_channel.go]: Remove all this commented code if it's not needed.

File: internal/highway/http/crud_bucket.go (hunk 1 above)
Comment (mcjcloud) [inline internal/highway/http/crud_bucket.go]: package is core but it's in the http directory. Rename to `http`.

File: internal/highway/http/crud_ipfs.go [hunk 29]
```diff
@@ -137,31 +92,15 @@ func (s *HighwayServer) DownloadBlobHTTP(c *gin.Context) {
...
 // @Schemes
 // @Description RemoveBlob deletes a file from storage given its CID.
 // @Tags Blob
 // @Produce json
 // @Success      200  {boolean}  success
 // @Failure      500  {string}  message
-// @Router /blob/remove/:cid [post]
-func (s *HighwayServer) RemoveBlobHTTP(c *gin.Context) {
+// @Router /v1/ipfs/remove/:cid [post]
+func (s *HighwayServer) RemoveBlob(c *gin.Context) {
```
Comment (mcjcloud) [inline internal/highway/http/crud_ipfs.go]: I think this whole method is unnecessary as an HTTP endpoint. This may remove a pin on IPFS but that's not something a dev really needs to do. Content is never completely erased from IPFS (and if it is we need auth here).

File: internal/highway/http/crud_object_test.go [hunk 30]
```diff
@@ -0,0 +1,58 @@
...
+					{
+						Name: "another label",
+						Kind: 0,
+					},
+				},
+			},
+			expected: ot.MsgCreateObjectResponse{},
+		},
+	}
+	for _, tt := range tests {
```
Comment (mcjcloud) [inline internal/highway/http/crud_object_test.go]: Tests aren't implemented

File: internal/highway/http/crud_registry.go [hunk 31]
```diff
@@ -0,0 +1,343 @@
...
+// @Summary Create WhoIs Entry
+// @Schemes
+// @Description This method takes a DIDDocument as an input along with the did of the account calling the TX, and verifies the signature. If succesful, and there is no existing WhoIs created for the user or application. Paramaters include: signature, diddocument, address, and whoIsType.
+// @Tags Registry
+// @Produce json
+// @Param 		 data body rt.MsgCreateWhoIs true "Parameters"
+// @Success 	 200  {object}  rt.MsgCreateWhoIsResponse
+// @Failure      500  {string}  message
+// @Router /v1/registry/create/whois [post]
+func (s *HighwayServer) CreateWhoIs(c *gin.Context) {
```
Comment (mcjcloud) [inline internal/highway/http/crud_registry.go]: No event emit for this one?

File: internal/highway/http/crud_registry.go [hunk 32]
```diff
@@ -0,0 +1,343 @@
...
+// @Summary Buy an Alias for a User
+// @Schemes
+// @Description This method purchases a user alias .snr domain i.e. {example}.snr or application alias extension i.e. example.snr/{appName}, and inserts it into the 'alsoKnownAs' field of the app's DIDDocument. Request fails when the DIDDoc type doesnt match, wallet balance is too low, the alias has already been purchased, creator is not listed as controller of DIDDoc, or WhoIs is deactivated.
+// @Tags Registry
+// @Produce json
+// @Param 		 data body rt.MsgBuyAlias true "Parameters"
+// @Success 	 200  {object}  rt.MsgBuyAliasResponse
+// @Failure      500  {string}  message
+// @Router /v1/registry/buy/alias/name [post]
+func (s *HighwayServer) BuyAlias(c *gin.Context) {
```
Comment (mcjcloud) [inline internal/highway/http/crud_registry.go]: The alias methods aren't under the `registry` endpoint, consider moving them to their own file `crud_alias.go`

File: internal/highway/http/crud_registry.go [hunk 33]
```diff
@@ -0,0 +1,343 @@
...
+
+// @Summary Start Register Name
+// @Schemes
+// @Description StartRegisterName starts the registration process and returns a PublicKeyCredentialCreationOptions. Initiating the registration process for a Sonr Account.
+// @Tags WebAuthn
+// @Produce json
+// @Success      200  {object}  map[string]interface{}
+// @Failure      500  {string}  message
+// @Router /v1/auth/register/start/:username [get]
+func (s *HighwayServer) StartRegisterName(w http.ResponseWriter, r *http.Request) {
```
Comment (mcjcloud) [inline internal/highway/http/crud_registry.go]: These methods aren't using gin. We should try to make all endpoints using gin or none.

File: internal/highway/http/crud_registry.go [hunk 34]
```diff
@@ -0,0 +1,343 @@
...
+	}
+
+	// Define Document
+	doc := did.Document{
+		ID:      *baseDid,
+		Context: []ssi.URI{*ctxUri},
+	}
+
+	// Create Controller DID with Device Info
+	controllerDid, err := did.ParseDID(fmt.Sprintf("did:sonr:%s#%s", s.Cosmos.Address(), s.Cosmos.AccountName()))
```
Comment (mcjcloud) [inline internal/highway/http/crud_registry.go]: Did construction should be in `did` pkg. We should avoid having "did:sonr/snr:" hard coded everywhere.

File: internal/highway/http/crud_registry.go [hunk 35]
```diff
@@ -0,0 +1,343 @@
...
+	// Unmarshal the credential into a COSEKey for us to extract the public key interface
+	coseKey := snrcrypto.COSEKey{}
+	err = cbor.Unmarshal(cred.PublicKey, &coseKey)
+	if err != nil {
+		log.Println(err)
+		jsonResponse(w, err.Error(), http.StatusBadRequest)
+		return
+	}
+
+	log.Println(coseKey)
```
Comment (mcjcloud) [inline internal/highway/http/crud_registry.go]: Is this necessary? This will be running in a server.

File: internal/highway/http/server.go [hunk 36]
```diff
@@ -0,0 +1,141 @@
...
+
+	// Create the IPFS Protocol
+	ipfs, err := ipfs.New(ctx, node)
+	if err != nil {
+		return nil, err
+	}
+
+	metrics, err := metrics.New(ctx, node)
+
+	// TODO: Enabling Matrix Protocol breaks build for Darwin
```
Comment (mcjcloud) [inline internal/highway/http/server.go]: Is this needed for ADR-001? If not I say create an issue for this and remove comments

File: internal/highway/x/prometheus/events.go [hunk 37]
```diff
@@ -0,0 +1,35 @@
+package metrics
+
+import (
+	"github.com/kataras/go-events"
+)
+
+const (
+	ON_OBJECT_ADD    = events.EventName("object_added")
```
Comment (mcjcloud) [inline internal/highway/x/prometheus/events.go:9]: nit: Using "ON" in the event name is redundant, since the listeners will say "on on".

`OBJECT_ADDED` would read better (same below).

File: internal/highway/x/prometheus/metrics.go [hunk 38]
```diff
@@ -0,0 +1,59 @@
...
+		Help:      "Counts the number of objects added to the highway",
+	})
+)
+
+func New(ctx context.Context, hn host.SonrHost) (*HighwayTelemetry, error) {
+	defer RegisterEvents()
+	return &HighwayTelemetry{endpoint: "/metrics"}, nil
+}
+
+func (ht *HighwayTelemetry) RecordMetrics() {
```
Comment (mcjcloud) [inline internal/highway/x/prometheus/metrics.go:47]: It looks like this just adds an operation every 2 seconds. If you want to count the total number of events, you should increase this in all the event handlers in `events.go`.

File: internal/highway/x/prometheus/events.go [hunk 39]
```diff
@@ -0,0 +1,35 @@
...
+
+func RegisterEvents() {
+	logger.Infof("Registering telemtry events")
+	events.AddListener(ON_OBJECT_ADD, func(params ...interface{}) {
+		objectsAdded.Inc()
+	})
+
+	events.AddListener(ON_OBJECT_REMOVE, func(params ...interface{}) {
+		logger.Debug("Object Removed event handler triggered")
+		objectsAdded.Dec()
```
Comment (mcjcloud) [inline internal/highway/x/prometheus/events.go:24]: Instead of decrementing this counter when an object is removed, it might be better to have a separate counter for removals. This way we can still know how many were originally added and we can figure out how many there are presently by subtracting.

Comment (mcjcloud) [reply internal/highway/x/prometheus/events.go:24]: This also applies to blobs.

File: internal/motor/motor.go [hunk 40]
```diff
@@ -0,0 +1 @@
+package motor
```
Comment (mcjcloud) [inline internal/motor/motor.go:1]: No content?

File: internal/motor/proto/core/v1/motor.proto [hunk 41]
```diff
@@ -0,0 +1,41 @@
...
+
+// Package Motor is used for defining a Motor node and its properties.
+package sonrio.motor.core.v1;
+
+import "core/v1/request.proto";
+import "core/v1/response.proto";
+option go_package = "github.com/sonr-io/sonr/pkg/motor";
+
+// MotorService is a RPC service for interfacing over the Motor node.
+service MotorService {
```
Comment (mcjcloud) [inline internal/motor/proto/core/v1/motor.proto:11]: Where is this being used?

File: internal/motor/proto/exchange/v1/exchange.proto [hunk 42]
```diff
@@ -0,0 +1,32 @@
...
+  string id = 1; // ID is the Message ID
+  core.v1.Payload payload = 2;    // Payload is the message data
+  core.v1.Peer from = 3;         // Users Peer Data
+  core.v1.Peer to = 4;           // Receivers Peer Data
+  core.v1.Metadata metadata = 5; // Metadata
+  int64 created_at = 6; // Timestamp
+}
+
+// Invitation Message sent on RPC
+message InviteRequest {
```
Comment (mcjcloud) [inline internal/motor/proto/exchange/v1/exchange.proto:19]: What does this invite you to do?

File: internal/motor/x/transmit/item.go [hunk 43]
```diff
@@ -7,14 +7,15 @@ import (
...
 
 	"github.com/libp2p/go-msgio"
-	"github.com/sonr-io/sonr/pkg/config"
-	v1 "go.buf.build/grpc/go/sonr-io/core/host/transmit/v1"
-	motor "go.buf.build/grpc/go/sonr-io/core/motor/v1"
-	types "go.buf.build/grpc/go/sonr-io/core/types/v1"
+	"github.com/sonr-io/sonr/pkg/fs"
+	"github.com/sonr-io/sonr/pkg/host"
+	t "github.com/sonr-io/sonr/types"
+	types "go.buf.build/grpc/go/sonr-io/motor/core/v1"
```
Comment (mcjcloud) [inline internal/motor/x/transmit/item.go]: nit: You're calling this motor in other places

File: internal/motor/x/transmit/item.go [hunk 44]
```diff
@@ -185,3 +186,19 @@ func URLCount(p *types.Payload) int {
 	// Return Count
 	return count
 }
+
+// SetPathFromFolder sets the path of the FileItem
+func SetPathFromFolder(f *types.FileItem, folder fs.Folder) (string, error) {
```
Comment (mcjcloud) [inline internal/motor/x/transmit/item.go]: Because this is modifying `f`, we should make it a receiver function.

```
func (f *types.FileItem) SetPathFromFolder(folder fs.Folder) error {
  ...
}
```

File: pkg/config/config.go [hunk 45]
```diff
@@ -126,86 +136,56 @@ func DefaultConfig() *Config {
...
-		cosmosclient.WithHome(c.CosmosHomePath),
-		cosmosclient.WithKeyringBackend(c.CosmosKeyringBackend),
-		cosmosclient.WithKeyringServiceName(c.CosmosKeyringServiceName))
-
-	return opts
+	return conf
 }
 
-// WebauthnConfig returns the configuration for the WebAuthn module
-func (c *Config) WebauthnConfig() *webauthn.Config {
```
Comment (mcjcloud) [inline pkg/config/config.go:155]: What's the reason behind this change? I notice in `pkg/client` you're creating a helper method to create a subset of the config. Why not use the existing strategy of having that in the config package?

File: pkg/did/credential.go [hunk 46]
```diff
@@ -0,0 +1,109 @@
...
+func SelectAuthenticator(att string, rrk *bool, uv string) p.AuthenticatorSelection {
+	return p.AuthenticatorSelection{
+		AuthenticatorAttachment: p.AuthenticatorAttachment(att),
+		RequireResidentKey:      rrk,
+		UserVerification:        p.UserVerificationRequirement(uv),
+	}
+}
+
+// WebauthnToAuthenticator will convert a webauthn authenticator to a did authenticator
+func WebauthnToAuthenticator(a webauthn.Authenticator) Authenticator {
```
Comment (mcjcloud) [inline pkg/did/credential.go]: nit: `WebauthnAuthenticatorToAuthenticator` is more accurate

File: pkg/did/did_test.go [hunk 47]
```diff
@@ -61,6 +58,12 @@ func TestParseDID(t *testing.T) {
 			t.Errorf("expected parsed did to be 'did:snr:123', got: %s", id.String())
 		}
 	})
+	t.Run("ok - parse a DID URL", func(t *testing.T) {
+		id, err := ParseDID("did:snr:123/path?query#fragment")
+		assert.Equal(t, "did:snr:123/path?query#fragment", id.String())
```
Comment (mcjcloud) [inline pkg/did/did_test.go]: You should assert that each part of the DID is what you expect, too.

File: pkg/did/did_test.go [hunk 48]
```diff
@@ -76,92 +79,3 @@ func TestParseDID(t *testing.T) {
 		assert.Equal(t, id.IDStrings[0], "123")
 	})
 }
-
-func TestMustParseDID(t *testing.T) {
```
Comment (mcjcloud) [inline pkg/did/did_test.go:80]: Why did you remove all of these tests? Many of the functions they test still exist.

File: pkg/did/document.go [hunk 49]
```diff
@@ -366,6 +377,9 @@ func NewVerificationMethod(id DID, keyType ssi.KeyType, controller DID, key cryp
 
 // JWK returns the key described by the VerificationMethod as JSON Web Key.
 func (v VerificationMethod) JWK() (jwk.Key, error) {
+	if v.Credential != nil {
+		// v.Credential.
```
Comment (mcjcloud) [inline pkg/did/document.go]: Incomplete?

File: pkg/did/document.go [hunk 50]
```diff
@@ -366,6 +377,9 @@ func NewVerificationMethod(id DID, keyType ssi.KeyType, controller DID, key cryp
...
+	}
 	if v.PublicKeyJwk == nil {
 		return nil, nil
```
Comment (mcjcloud) [inline pkg/did/document.go]: Should there be an error here?

File: pkg/did/document.go [hunk 51]
```diff
@@ -470,3 +484,100 @@ func resolveVerificationRelationship(reference DID, methods []*VerificationMetho
 	}
 	return nil
 }
+
+// User ID according to the Relying Party
+func (w *Document) WebAuthnID() []byte {
```
Comment (mcjcloud) [inline pkg/did/document.go]: Why does this return a byte array? If it's needed as a byte array elsewhere it makes more sense to do `[]byte(WebAuthnId())` there.

Comment (mcjcloud) [reply pkg/did/document.go]: Also, why are these all named `Webauthn`? The ID, name, etc aren't specifically related to webauthn if I understand correctly.

File: pkg/did/document.go [hunk 52]
```diff
@@ -470,3 +484,100 @@ func resolveVerificationRelationship(reference DID, methods []*VerificationMetho
...
+	return []byte(w.ID.String())
+}
+
+// User Name according to the Relying Party
+func (w *Document) WebAuthnName() string {
+	if w.AlsoKnownAs != nil {
+		if len(w.AlsoKnownAs) > 0 {
```
Comment (mcjcloud) [inline pkg/did/document.go]: nit: These can be combined with `&&`

File: pkg/did/document.go [hunk 53]
```diff
@@ -470,3 +484,100 @@ func resolveVerificationRelationship(reference DID, methods []*VerificationMetho
...
+			return w.AlsoKnownAs[0]
```
Comment (mcjcloud) [inline pkg/did/document.go]: What is the purpose of this function? Should also known as be considered to be the name? What if they have more than 1—-why are we always using the first one?

File: pkg/did/document.go [hunk 54]
```diff
@@ -470,3 +484,100 @@ func resolveVerificationRelationship(reference DID, methods []*VerificationMetho
...
+}
+
+// Display Name of the user
+func (w *Document) WebAuthnDisplayName() string {
+	return w.ID.ID
+}
+
+// User's icon url
+func (w *Document) WebAuthnIcon() string {
+	return ""
```
Comment (mcjcloud) [inline pkg/did/document.go]: Incomplete?

File: pkg/did/document.go [hunk 55]
```diff
@@ -470,3 +484,100 @@ func resolveVerificationRelationship(reference DID, methods []*VerificationMetho
...
+}
+
+// Credentials owned by the user
+func (w *Document) WebAuthnCredentials() []webauthn.Credential {
```
Comment (mcjcloud) [inline pkg/did/document.go]: Why do we convert the webauthn credential to our own model only to convert it back to a `webauthn.Credential`?

File: pkg/did/document.go [hunk 56]
```diff
@@ -470,3 +484,100 @@ func resolveVerificationRelationship(reference DID, methods []*VerificationMetho
...
+					SignCount:    vm.Credential.Authenticator.SignCount,
+					CloneWarning: vm.Credential.Authenticator.CloneWarning,
+				},
+			})
+		}
+	}
+	return credentials
+}
+
+// TODO: JWT verification for JWK
```
Comment (mcjcloud) [inline pkg/did/document.go]: Resolve this

File: pkg/did/jwe.go [hunk 57]
```diff
@@ -3,58 +3,35 @@ package did
...
 	if vm == nil {
 		return "", errors.New("Document VerificationMethod not found")
 	}
 
-	publicKey, err := vm.PublicKey()
-	if err != nil {
-		return "", err
+	// check type of key
+	var key interface{}
+	switch vm.Type {
```
Comment (mcjcloud) [inline pkg/did/jwe.go]: `vm.PublicKey()` already does a check on the type, so this check is redundant.

File: pkg/host/common.go [hunk 58]
```diff
@@ -0,0 +1,267 @@
...
+}
+
+// HostID returns the ID of the Host
+func (n *hostImpl) HostID() peer.ID {
+	return n.host.ID()
+}
+
+// Ping sends a ping to the peer
+func (n *hostImpl) Ping(pid string) error {
+	return nil
```
Comment (mcjcloud) [inline pkg/host/common.go:42]: Incomplete?

File: pkg/host/common.go [hunk 59]
```diff
@@ -0,0 +1,267 @@
...
+}
+
+// Role returns the role of the node
+func (n *hostImpl) Role() config.Role {
+	return n.config.Role
+}
+
+// AuthenticateMessage Authenticates incoming p2p message
+func (n *hostImpl) AuthenticateMessage(msg proto.Message, metadata *t.Metadata) bool {
+	// store a temp ref to signature and remove it from message data
```
Comment (mcjcloud) [inline pkg/host/common.go:62]: Doesn't look like anything is being removed from `msg` Is this temp ref necessary?

File: pkg/host/common.go [hunk 60]
```diff
@@ -0,0 +1,267 @@
...
+	return ed25519.PrivateKey(buf), nil
+}
+
+// Role returns the role of the node
+func (n *hostImpl) Role() config.Role {
+	return n.config.Role
+}
+
+// AuthenticateMessage Authenticates incoming p2p message
+func (n *hostImpl) AuthenticateMessage(msg proto.Message, metadata *t.Metadata) bool {
```
Comment (mcjcloud) [inline pkg/host/common.go]: nit: `IsAuthenticMessage(...)` is more accurate since this returns a `bool`.

File: pkg/host/common.go [hunk 61]
```diff
@@ -0,0 +1,267 @@
...
+	return hn.host.Connect(hn.ctx, pi)
+}
+
+// HandlePeerFound is to be called when new  peer is found
+func (hn *hostImpl) HandlePeerFound(pi peer.AddrInfo) {
+	hn.mdnsPeerChan <- pi
+}
+
+// HasRouting returns no-error if the host is ready for connect
+func (h *hostImpl) HasRouting() error {
```
Comment (mcjcloud) [inline pkg/host/common.go]: This looks like something that should return `bool` instead of `error`.

File: pkg/host/common.go [hunk 62]
```diff
@@ -0,0 +1,267 @@
...
+	if err := w.WriteMsg(bin); err != nil {
+		return err
+	}
+	return nil
+}
+
+// Stat returns the host stat info
+func (hn *hostImpl) Stat() (map[string]string, error) {
+	// Return Host Stat
+	return map[string]string{
```
Comment (mcjcloud) [inline pkg/host/common.go]: Making this a struct would make things clearer for any caller.

File: pkg/host/common.go [hunk 63]
```diff
@@ -0,0 +1,267 @@
...
+		"ID":        hn.host.ID().String(),
+		"Status":    hn.status.String(),
+		"MultiAddr": hn.host.Addrs()[0].String(),
+	}, nil
+}
+
+// Serve handles incoming peer Addr Info
+func (hn *hostImpl) Serve() {
```
Comment (mcjcloud) [inline pkg/host/common.go:250]: Can you add some comments explaining what's happening here?

File: pkg/host/common.go [hunk 64]
```diff
@@ -0,0 +1,267 @@
...
+				continue
+			}
+		case <-hn.ctx.Done():
+			return
+		}
+	}
+}
+
+// VerifyData verifies incoming p2p message data integrity
+func (n *hostImpl) VerifyData(data []byte, signature []byte, peerId peer.ID, pubKeyData []byte) bool {
```
Comment (mcjcloud) [inline pkg/host/common.go]: This should return `error`, since all the errors popping up in this function will just be silenced as is.

Comment (mcjcloud) [inline pkg/host/common.go]: nit: This can be shortened to
```
func (n *hostImpl) VerifyData(data, signature, pubKeyData []byte, peerId peer.ID) error {
  ..
}
```

File: pkg/host/host.go [hunk 65]
```diff
@@ -0,0 +1,241 @@
...
+	"github.com/pion/webrtc/v3"
+	"github.com/sonr-io/sonr/pkg/config"
+	types "go.buf.build/grpc/go/sonr-io/motor/core/v1"
+)
+
+// hostImpl type - a p2p host implementing one or more p2p protocols
+type hostImpl struct {
+	// Standard Node Implementation
+	host host.Host
+	SonrHost
```
Comment (mcjcloud) [inline pkg/host/host.go]: This line shouldn't be here if you're trying to implement this interface. In fact, it silences any errors that arise from it not being implemented fully.

File: pkg/host/host.go [hunk 66]
```diff
@@ -0,0 +1,241 @@
...
+	hn := &hostImpl{
+		ctx:          ctx,
+		status:       Status_IDLE,
+		mdnsPeerChan: make(chan peer.AddrInfo),
+		config:       c,
+		events:       events.New(),
+	}
+
+	// findPrivKey returns the private key for the host.
+	findPrivKey := func() (crypto.PrivKey, error) {
```
Comment (mcjcloud) [inline pkg/host/host.go:62]: Is this meant to create a random private key? If so it should be called `genPrivKey` or something to that effect.

File: pkg/host/host.go [hunk 67]
```diff
@@ -0,0 +1,241 @@
...
+
+	// Bootstrap DHT
+	if err := hn.Bootstrap(context.Background()); err != nil {
+		hn.SetStatus(Status_FAIL)
+		return nil, err
+	}
+
+	// Connect to Bootstrap Nodes
+	for _, pi := range c.Libp2pBootstrapPeers {
+		if err := hn.Connect(pi); err != nil {
```
Comment (mcjcloud) [inline pkg/host/host.go:104]: What if all of these fail?

File: pkg/host/host.go [hunk 68]
```diff
@@ -0,0 +1,241 @@
...
+	// Initialize Discovery for DHT
+	if err := hn.createDHTDiscovery(c); err != nil {
+		// Check if we need to close the listener
+		hn.SetStatus(Status_FAIL)
+		return nil, err
+	}
+
+	// Initialize Discovery for MDNS
+	if !c.Libp2pMdnsDisabled && hn.Role() != config.Role_HIGHWAY {
+		// hn.createMdnsDiscovery(config)
```
Comment (mcjcloud) [inline pkg/host/host.go:120]: Incomplete?

File: pkg/host/host.go [hunk 69]
```diff
@@ -0,0 +1,241 @@
...
+	}
+
+	hn.SetStatus(Status_READY)
+	go hn.Serve()
+	return hn, nil
+}
+
+// NewWasmHost Creates a Sonr libp2p Host with the given config and wasm module
+func NewWasmHost(ctx context.Context, c *config.Config) (SonrHost, error) {
```
Comment (mcjcloud) [inline pkg/host/host.go:129]: Noticing a lot of duplicate code between this function and the one above. Try moving duplicate code into a helper function.

File: pkg/host/host.go [hunk 70]
```diff
@@ -0,0 +1,241 @@
...
+	hn.dhtPeerChan, err = routingDiscovery.FindPeers(hn.ctx, c.Libp2pRendezvous, c.Libp2pTTL)
+	if err != nil {
+		hn.SetStatus(Status_FAIL)
+		return err
+	}
+	hn.SetStatus(Status_READY)
+	return nil
+}
+
+// TODO Migrate MDNS Service to latesat libp2p spec
```
Comment (mcjcloud) [inline pkg/host/host.go:230]: Delete commented code

File: testutil/sample/sample.go [hunk 71]
```diff
@@ -11,3 +12,16 @@ func AccAddress() string {
 	addr := pk.Address()
 	return sdk.AccAddress(addr).String()
 }
+
+// Mock Credential object from webauthn test bench https://github.com/psteniusubi/webauthn-tester
+func CreateMockCredential() *did.Credential {
```
Comment (mcjcloud) [inline testutil/sample/sample.go:25]: This method is defined in 3 different locations:
* Here
* didutil/existing_did.go
* registry/simulation/simap.go

File: types/codes.go [hunk 72]
```diff
@@ -0,0 +1 @@
+package types
```
Comment (mcjcloud) [inline types/codes.go:1]: No content?

File: types/events.go [hunk 73]
```diff
@@ -0,0 +1,23 @@
+package types
+
+import "github.com/kataras/go-events"
+
+const (
+	// ON_REFRESH is an event type for when the LobbyProtocol is refreshed
+	ON_REFRESH = events.EventName("on_refresh")
```
Comment (mcjcloud) [inline types/events.go:7]: Same as before comment: remove "ON" from the name of the events. (i.e. `LOBBY_PROTOCOL_REFRESHED`).

All of these names could include more context too.

File: x/bucket/keeper/msg_server_create_bucket.go [hunk 74]
```diff
@@ -41,7 +36,7 @@ func (k msgServer) CreateBucket(goCtx context.Context, msg *types.MsgCreateBucke
 	// Create a new channel record
 	newWhichIs := types.WhichIs{
 		Did:       did.ID,
-		Creator:   msg.GetSession().Creator(),
+		Creator:   msg.Creator,
```
Comment (mcjcloud) [inline x/bucket/keeper/msg_server_create_bucket.go:39]: Won't `did.ID` and `msg.Creator` always be the same?

File: x/channel/keeper/msg_server_create_channel.go [hunk 75]
```diff
@@ -42,7 +37,7 @@ func (k msgServer) CreateChannel(goCtx context.Context, msg *types.MsgCreateChan
 	// Create a new channel record
 	newHowis := types.HowIs{
 		Did:       did.ID,
-		Creator:   msg.GetSession().Creator(),
+		Creator:   msg.GetCreator(),
```
Comment (mcjcloud) [inline x/channel/keeper/msg_server_create_channel.go:40]: Same as previous comment. Probably applies to all of these

File: x/registry/client/cli/query.go [hunk 76]
```diff
@@ -27,6 +27,9 @@ func GetQueryCmd(queryRoute string) *cobra.Command {
 	cmd.AddCommand(CmdQueryParams())
 	cmd.AddCommand(CmdListWhoIs())
 	cmd.AddCommand(CmdShowWhoIs())
+	cmd.AddCommand(CmdWhoIsAlias())
+
```
Comment (mcjcloud) [inline x/registry/client/cli/query.go]: nit: newline

File: x/registry/client/cli/query_who_is_alias.go [hunk 77]
```diff
@@ -5,41 +5,42 @@ import (
...
 )
 
 var _ = strconv.Itoa(0)
 
-func CmdUpdateName() *cobra.Command {
+func CmdWhoIsAlias() *cobra.Command {
 	cmd := &cobra.Command{
-		Use:   "update-name [name]",
-		Short: "Broadcast message update-name",
+		Use:   "who-is-alias [alias]",
```
Comment (mcjcloud) [inline x/registry/client/cli/query_who_is_alias.go:16]: How are these CLI commands invoked? If these are part of sonrd then they should be in the `cmd/sonrd` folder if possible.

File: x/registry/keeper/msg_server_buy_alias.go [hunk 78]
```diff
@@ -0,0 +1,57 @@
+package keeper
+
+import (
+	"context"
+
+	sdk "github.com/cosmos/cosmos-sdk/types"
+	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
+	"github.com/sonr-io/sonr/pkg/did"
+	"github.com/sonr-io/sonr/x/registry/types"
```
Comment (mcjcloud) [inline x/registry/keeper/msg_server_buy_alias.go:8]: nit: Rename to something like `registrytypes`

File: x/registry/keeper/msg_server_buy_alias.go [hunk 79]
```diff
@@ -0,0 +1,57 @@
...
+
+	// Get whois from Owner
+	// TODO: Implement Multisig for root level owner
+	whois, isFound := k.GetWhoIsFromOwner(ctx, msg.Creator)
+	if !isFound {
+		return nil, sdkerrors.Wrapf(types.ErrControllerNotFound, "creator %s", msg.Creator)
+	}
+
+	// Unmarshal DIDDoc from whois
+	doc := did.Document{}
```
Comment (mcjcloud) [inline x/registry/keeper/msg_server_buy_alias.go]: nit: `var doc did.Document`

File: x/registry/keeper/msg_server_buy_alias.go [hunk 80]
```diff
@@ -0,0 +1,57 @@
...
+	err := doc.UnmarshalJSON(whois.GetDidDocument())
+	if err != nil {
+		return nil, sdkerrors.Wrap(types.ErrDidDocumentInvalid, "Failed to unmarshal DID document")
+	}
+
+	// Convert owner and buyer address strings to sdk.AccAddress
+	buyer, _ := sdk.AccAddressFromBech32(msg.Creator)
+	minPrice := sdk.Coins{sdk.NewInt64Coin("snr", 10)}
```
Comment (mcjcloud) [inline x/registry/keeper/msg_server_buy_alias.go]: This should probably be configurable instead of hard-coded

File: x/registry/keeper/msg_server_buy_alias.go [hunk 81]
```diff
@@ -0,0 +1,57 @@
...
+	err = k.bankKeeper.SendCoinsFromAccountToModule(ctx, buyer, types.ModuleName, minPrice)
+	if err != nil {
+		return nil, sdkerrors.Wrap(sdkerrors.ErrUnknownRequest, "Not enough snr coins to buy name")
```
Comment (mcjcloud) [inline x/registry/keeper/msg_server_buy_alias.go]: Is this the only type of error that could come from `SendCoinsFromAccountToModule`? I think the original error should be wrapped and propagated as well.

File: x/registry/keeper/msg_server_buy_alias.go [hunk 82]
```diff
@@ -0,0 +1,57 @@
...
+	}
+
+	// Create an updated whois record
+	doc.AddAlias(msg.GetName())
+	whois.CopyFromDidDocument(&doc)
```
Comment (mcjcloud) [inline x/registry/keeper/msg_server_buy_alias.go]: The error here is being ignored.

File: x/registry/keeper/msg_server_sell_alias.go [hunk 83]
```diff
@@ -0,0 +1,40 @@
...
+)
+
+func (k msgServer) SellAlias(goCtx context.Context, msg *types.MsgSellAlias) (*types.MsgSellAliasResponse, error) {
+	ctx := sdk.UnwrapSDKContext(goCtx)
+
+	// Check if Alias exists
+	whoIs, aliasIsFound := k.GetWhoIsFromAlias(ctx, msg.GetAlias())
+	// If a name is found in store
+	if aliasIsFound {
+		return nil, sdkerrors.Wrap(types.ErrAliasUnavailable, "Name already has an owner")
```
Comment (mcjcloud) [inline x/registry/keeper/msg_server_sell_alias.go]: We should expect that the alias is found if someone is selling it. There should instead be a check that the alias actually belongs to the person trying to sell it.

File: x/registry/keeper/msg_server_buy_alias.go [hunk 84]
```diff
@@ -0,0 +1,57 @@
...
+	// Check if Alias exists
+	_, aliasIsFound := k.GetWhoIsFromAlias(ctx, msg.Name)
+	// If a name is found in store
+	if aliasIsFound {
+		return nil, sdkerrors.Wrap(types.ErrAliasUnavailable, "Name already has an owner")
+	}
+
+	// Get whois from Owner
+	// TODO: Implement Multisig for root level owner
+	whois, isFound := k.GetWhoIsFromOwner(ctx, msg.Creator)
```
Comment (mcjcloud) [inline x/registry/keeper/msg_server_buy_alias.go:26]: How is the `Creator` field being populated? Seems like with this setup anybody can arbitrarily buy aliases for anyone else

File: x/registry/keeper/msg_server_sell_alias.go [hunk 85]
```diff
@@ -0,0 +1,40 @@
...
+	}
+
+	// If alias not found
+	if !aliasIsFound {
+		return nil, sdkerrors.Wrapf(types.ErrAliasNotFound, "Alias %s not found", msg.GetAlias())
+	}
+
+	// Find associated Alias in whoIs
+	for _, a := range whoIs.Alias {
+		if a.GetName() == msg.GetAlias() {
```
Comment (mcjcloud) [inline x/registry/keeper/msg_server_sell_alias.go]: This will always find a match since you're using the alias in the request to find the `whoIs`. With the way this function is setup, anybody can put an alias up for sell by just making this call.

File: x/registry/keeper/msg_server_transfer_alias.go [hunk 86]
```diff
@@ -0,0 +1,58 @@
...
+		return nil, sdkerrors.Wrapf(types.ErrAliasNotFound, "alias %s", msg.GetAlias())
+	}
+
+	// Convert Alias Owner address strings to sdk.AccAddress
+	aliasOwner, err := sdk.AccAddressFromBech32(msg.GetRecipient())
+	if err != nil {
+		return nil, sdkerrors.Wrapf(err, "alias owner %s", msg.GetRecipient())
+	}
+
+	//TODO: put this in escrow to mitigate transfer/alias race condition attacks
```
Comment (mcjcloud) [inline x/registry/keeper/msg_server_transfer_alias.go]: Can you link an issue here?

File: x/registry/keeper/msg_server_transfer_alias.go [hunk 87]
```diff
@@ -0,0 +1,58 @@
...
+
+	// Check if Alias exists if not return error
+	_, aliasIsFound := k.GetWhoIsFromAlias(ctx, msg.GetAlias())
+	// If a name is not found in store return error
+	if !aliasIsFound {
+		return nil, sdkerrors.Wrap(types.ErrAliasUnavailable, "Name does not exist")
+	}
+
+	// Get whois from Owner
+	// TODO: Implement Multisig for root level owner
```
Comment (mcjcloud) [inline x/registry/keeper/msg_server_transfer_alias.go]: Link issue for multisig

File: x/registry/types/message_buy_alias.go [hunk 88]
```diff
@@ -0,0 +1,62 @@
...
+
+func (msg *MsgBuyAlias) GetSigners() []sdk.AccAddress {
+	creator, err := sdk.AccAddressFromBech32(msg.Creator)
+	if err != nil {
+		panic(err)
+	}
+	return []sdk.AccAddress{creator}
+}
+
+func (msg *MsgBuyAlias) GetSignBytes() []byte {
```
Comment (mcjcloud) [inline x/registry/types/message_buy_alias.go:55]: nit: Signed?

File: x/registry/types/who_is.go [hunk 89]
```diff
@@ -2,214 +2,93 @@ package types
...
-		Type:        rt.WhoIs_Type(doc.GetType()),
-		Name:        doc.GetName(),
-		Did:         doc.GetDid(),
-		Document:    doc.GetDocument(),
-		Metadata:    doc.GetMetadata(),
-		Credentials: NewCredentialListToBuf(doc.GetCredentials()),
+// ContainsController checks if the controller is in the list of controllers of the whois
+func (w *WhoIs) ContainsController(target string) bool {
+	// Validates DID String
+	if _, err := did.ParseDID(target); err != nil {
```
Comment (mcjcloud) [inline x/registry/types/who_is.go:25]: This check is extraneous because a malformed controller won't exist in the list anyway.

File: x/registry/types/who_is.go [hunk 90]
```diff
@@ -2,214 +2,93 @@ package types
...
-	m := w.GetMetadata()
-	if m == nil {
-		return "", fmt.Errorf("no metadata found")
-	}
-
-	if an := m["app_name"]; an != "" {
-		return an, nil
+// UnmarshalDidDocument unmarshals the whois document into a DID document
+func (w *WhoIs) UnmarshalDidDocument() (*did.Document, error) {
+	doc := did.Document{}
```
Comment (mcjcloud) [inline x/registry/types/who_is.go]: nit: `var doc did.Document`

File: x/registry/types/who_is.go [hunk 91]
```diff
@@ -2,214 +2,93 @@ package types
...
-	for _, cred := range w.GetCredentials() {
-		descriptor := protocol.CredentialDescriptor{
-			Type:         protocol.PublicKeyCredentialType,
-			CredentialID: cred.ID,
+	for _, a := range as {
+		if !w.ContainsAlias(a) {
+			w.Alias = append(w.Alias, &Alias{
+				Name:      a,
+				IsForSale: false,
+				Amount:    10,
```
Comment (mcjcloud) [inline x/registry/types/who_is.go]: This should be unset if the item is not for sell (0 or -1 maybe)

**Review by mcjcloud — CHANGES_REQUESTED** [review]

File: cmd/sonrd/didutil/existing_did.go (hunk 13 above)
Comment (joshLong145) [reply cmd/sonrd/didutil/existing_did.go]: There is a command to generate a did document which you provide the path to. In my testing it doesn't persist the updates to the file however

File: cmd/motor-lib/wasm.go (hunk 11 above)
Comment (joshLong145) [reply cmd/motor-lib/wasm.go:1]: Seems to the motor stand up operation commented for I presume is wasm conpilation

File: cmd/motor-lib/bind.go (hunk 10 above)
Comment (joshLong145) [reply cmd/motor-lib/bind.go:9]: Seems to the motor stand up operation commented for what I presume is the wasm target compilation

File: internal/highway/x/prometheus/events.go (hunk 39 above)
Comment (joshLong145) [reply internal/highway/x/prometheus/events.go:24]: This was from a pr I had merged. I was thinking it might be better to track individually. I'll make a pr updating this afterwards

File: internal/highway/x/prometheus/metrics.go (hunk 38 above)
Comment (joshLong145) [reply internal/highway/x/prometheus/metrics.go:47]: This is a needed counter for adding telemetry from system resources. Used under the hood to keep the collector updating

File: cmd/motor-lib/wasm.go [hunk 92]
```diff
@@ -0,0 +1,24 @@
...
+import (
+	"context"
+
+	"github.com/sonr-io/sonr/pkg/config"
+	"github.com/sonr-io/sonr/pkg/host"
+)
+
+func main() {
+	config := config.DefaultConfig(config.Role_MOTOR)
+	_, err := host.NewWasmHost(context.Background(), config)
```
Comment (joshLong145) [inline cmd/motor-lib/wasm.go]: does not appear we do anything with the returned "host" for the wasm target

File: internal/highway/http/crud_bucket.go (hunk 27 above)
Comment (joshLong145) [reply internal/highway/http/crud_bucket.go:26]: This is done through many of the http endpoints, think we should say in general check for responses to map to a scoped return value.

File: internal/highway/http/crud_object_test.go [hunk 93]
```diff
@@ -0,0 +1,58 @@
...
+	"context"
+	"errors"
+	"testing"
+
+	hw "github.com/sonr-io/sonr/internal/highway"
+	ot "github.com/sonr-io/sonr/x/object/types"
+	"github.com/stretchr/testify/require"
+)
+
+func TestMsgCreateObject_ValidateBasic(t *testing.T) {
```
Comment (joshLong145) [inline internal/highway/http/crud_object_test.go]: This should be removed as it does depdends on the block chain to be running and to connect. will fail in a unit test enviorment.

File: internal/highway/http/crud_registry.go [hunk 94]
```diff
@@ -0,0 +1,343 @@
...
+	// Create DID Context
+	ctxUri, err := ssi.ParseURI("https://www.w3.org/ns/did/v1")
+	if err != nil {
+		log.Println(err)
+		jsonResponse(w, err.Error(), http.StatusBadRequest)
+		return
+	}
+
+	// Parse did from username
+	baseDid, err := did.ParseDID(fmt.Sprintf("did:sonr:%s", s.Cosmos.Address()))
```
Comment (joshLong145) [inline internal/highway/http/crud_registry.go]: Should be moved to did utility

File: internal/highway/x/matrix/config.go [hunk 95]
```diff
@@ -42,16 +49,64 @@ func defaultConfig(host host.SonrHost) (config.Dendrite, error) {
 	return cfg, nil
 }
 
-func (p *MatrixProtocol) Init() {
+func (p *MatrixProtocol) setupMonolith() error {
```
Comment (joshLong145) [inline internal/highway/x/matrix/config.go:52]: function should be renamed to better sugest standing up of matrix protocol server

File: internal/highway/x/matrix/config.go [hunk 96]
```diff
@@ -42,16 +49,64 @@ func defaultConfig(host host.SonrHost) (config.Dendrite, error) {
...
+	asAPI := appservice.NewInternalAPI(p.Base, userAPI, rsAPI)
+	rsAPI.SetAppserviceAPI(asAPI)
+	fsAPI := federationapi.NewInternalAPI(
+		p.Base, p.fedClient, rsAPI, p.Base.Caches, nil, true,
+	)
+	keyRing := fsAPI.KeyRing()
+	rsAPI.SetFederationAPI(fsAPI, keyRing)
+	provider := newPublicRoomsProvider(p.Host.Pubsub(), rsAPI)
+	err := provider.Start()
+	if err != nil {
```
Comment (joshLong145) [inline internal/highway/x/matrix/config.go:70]: Should be more info logging in the stand up to provide context for debugging

File: internal/motor/x/discover/local.go [hunk 97]
```diff
@@ -7,11 +7,11 @@ import (
 	"github.com/libp2p/go-libp2p-core/peer"
 	ps "github.com/libp2p/go-libp2p-pubsub"
 
-	"github.com/sonr-io/sonr/internal/host"
-	"github.com/sonr-io/sonr/pkg/config"
-	v1 "go.buf.build/grpc/go/sonr-io/core/host/discover/v1"
-	motor "go.buf.build/grpc/go/sonr-io/core/motor/v1"
-	types "go.buf.build/grpc/go/sonr-io/core/types/v1"
+	"github.com/sonr-io/sonr/pkg/host"
+	t "github.com/sonr-io/sonr/types"
```
Comment (joshLong145) [inline internal/motor/x/discover/local.go:11]: naming of types pkg is inconsistent in imports. we should standardize on an override for the types pkg through all files.

File: cmd/sonrd/didutil/cmd.go [hunk 98]
```diff
@@ -0,0 +1,62 @@
...
+			} else {
+				err = surveyExistingDid()
+				cobra.CheckErr(err)
+			}
+
+			return nil
+		},
+	}
+
+	flags.AddTxFlagsToCmd(cmd)
```
Comment (joshLong145) [inline cmd/sonrd/didutil/cmd.go]: There doesnt seem to be an obvious point where the generated did doc is persisted to disk. in my testing updating and saving do not honor the opperation

File: cmd/sonrd/didutil/existing_did.go [hunk 99]
```diff
@@ -0,0 +1,169 @@
...
+		prompt := &survey.Multiline{
+			Message: "Paste your JWE object here:",
+		}
+		survey.AskOne(prompt, &text)
+		// Decrypt JWE
+		buf, err := doc.DecryptJWE(doc.Controller[0], text)
+		if err != nil {
+			return err
+		}
+		fmt.Println(string(buf))
```
Comment (joshLong145) [inline cmd/sonrd/didutil/existing_did.go]: Many of these cases end incosistently and do not seem to persist the operation

File: cmd/highwayd/index.html (hunk 5 above)
Comment (prdlk) [reply cmd/highwayd/index.html]: Yeah realistically this file shouldnt even exist. Its getting embedded to run right now.

File: x/registry/types/message_buy_alias.go (hunk 88 above)
Comment (prdlk) [reply x/registry/types/message_buy_alias.go:55]: This is implementation method for the underlying cosmos message - cant change function name

File: x/registry/types/who_is.go (hunk 90 above)
Comment (prdlk) [reply x/registry/types/who_is.go]: good catch

File: x/registry/types/who_is.go (hunk 91 above)
Comment (prdlk) [reply x/registry/types/who_is.go]: True will do

File: pkg/did/credential.go [hunk 100]
```diff
@@ -0,0 +1,109 @@
...
+//
+//  If the signature counter value authData.signCount is
+//
+//  → Greater than the signature counter value stored in conjunction with credential’s id attribute.
+//  Update the stored signature counter value, associated with credential’s id attribute, to be the value of
+//  authData.signCount.
+//
+//  → Less than or equal to the signature counter value stored in conjunction with credential’s id attribute.
+//  This is a signal that the authenticator may be cloned, see CloneWarning above for more information.
+func (a *Authenticator) UpdateCounter(authDataCount uint32) {
```
Comment (joshLong145) [inline pkg/did/credential.go:103]: This method is unused currently

File: pkg/host/common.go [hunk 101]
```diff
@@ -0,0 +1,267 @@
...
+}
+
+// PrivateKey returns the private key of the node
+func (n *hostImpl) PrivateKey() (ed25519.PrivateKey, error) {
+	// Get Raw Private Key
+	buf, err := n.privKey.Raw()
+	if err != nil {
+		return nil, err
+	}
+	return ed25519.PrivateKey(buf), nil
```
Comment (joshLong145) [inline pkg/host/common.go:52]: does this mean that the host can only support ed25519 keys?

File: pkg/host/common.go [hunk 102]
```diff
@@ -0,0 +1,267 @@
...
+			}
+		case <-hn.ctx.Done():
+			return
+		}
+	}
+}
+
+// VerifyData verifies incoming p2p message data integrity
+func (n *hostImpl) VerifyData(data []byte, signature []byte, peerId peer.ID, pubKeyData []byte) bool {
+	key, err := crypto.UnmarshalPublicKey(pubKeyData)
```
Comment (joshLong145) [inline pkg/host/common.go:272]: Does this lock us into a single key format? it doesnt seem like we will be able to support atribitrary key types (unless this is just for wallets) this seems incompatible with did verification method key types

File: x/registry/keeper/msg_server_transfer_alias.go (hunk 87 above)
Comment (prdlk) [reply x/registry/keeper/msg_server_transfer_alias.go]: #322 Is it

File: internal/highway/http/crud_object.go [hunk 103]
```diff
@@ -0,0 +1,117 @@
...
+// @Summary Create Object
+// @Schemes
+// @Description CreateObject creates a Object for a registered application
+// @Tags Object
+// @Produce json
+// @Param 		 data body ot.MsgCreateObject true "Parameters"
+// @Success      200  {object}  ot.MsgCreateObjectResponse
+// @Failure      500  {string}  message
+// @Router /v1/object/create [post]
+func (s *HighwayServer) CreateObject(c *gin.Context) {
```
Comment (joshLong145) [inline internal/highway/http/crud_object.go]: Create object fails with the sample post man data due to invalid creator name

File: cmd/highwayd/main.go (hunk 6 above)
Comment (prdlk) [reply cmd/highwayd/main.go]: Moved to Highway, added config options for WebAuthNFSDir and WebAuthNAddress

File: cmd/highwayd/index.html (hunk 5 above)
Comment (prdlk) [reply cmd/highwayd/index.html]: Created templates directory - proper golang usage of this

**Comment by joshLong145** [comment]
Noting that msg_server_who_is_test are also failing on create update and delete operations

File: pkg/host/common.go [hunk 104]
```diff
@@ -0,0 +1,267 @@
...
+	}
+
+	// extract node id from the provided public key
+	idFromKey, err := peer.IDFromPublicKey(key)
+	if err != nil {
+		return false
+	}
+
+	// verify that message author node id matches the provided node public key
+	if idFromKey != peerId {
```
Comment (joshLong145) [inline pkg/host/common.go:284]: Should be updated as it appears peerId has become the DID

File: pkg/host/host.go [hunk 105]
```diff
@@ -0,0 +1,241 @@
...
+		return nil, err
+	}
+
+	// Fetch the private key.
+	hn.privKey, err = findPrivKey()
+	if err != nil {
+		return nil, err
+	}
+
+	maddr, err := ma.NewMultiaddr("/ip4/127.0.0.1/tcp/9090/http/p2p-webrtc-direct")
```
Comment (joshLong145) [inline pkg/host/host.go:155]: Should be moved to the host config or made an env variable

**Review by joshLong145 — CHANGES_REQUESTED** [review]
See review comments and top level comments left. can also assist with changes

File: internal/highway/http/crud_ipfs.go [hunk 106]
```diff
@@ -42,8 +21,8 @@ func (s *HighwayServer) UploadBlob(ctx context.Context, req *highwayv1.MsgUpload
 // @Produce json
 // @Success      200  {string}  cid
 // @Failure      500  {string}  message
-// @Router /blob/upload [post]
-func (s *HighwayServer) UploadBlobHTTP(c *gin.Context) {
+// @Router /v1/ipfs/upload [post]
```
Comment (joshLong145) [inline internal/highway/http/crud_ipfs.go]: this file should be renamed back to `crud_blob` and routes should be changed back to `blob` as well

File: internal/highway/http/crud_object_test.go (hunk 30 above)
Comment (joshLong145) [reply internal/highway/http/crud_object_test.go]: there is a test commented out in the run definition. this file should be deleted, as the tests wont run isolated (needs chain running to pass)

File: x/registry/keeper/msg_server_buy_alias.go (hunk 84 above)
Comment (joshLong145) [reply x/registry/keeper/msg_server_buy_alias.go:26]: this is populated by the the creator of the `MsgBuyAlias` which i think means any Creator can be specified in the request and will be respected as the point of transfer.

File: x/registry/keeper/msg_server_buy_alias.go [hunk 107]
```diff
@@ -0,0 +1,57 @@
...
+
+	// Unmarshal DIDDoc from whois
+	doc := did.Document{}
+	err := doc.UnmarshalJSON(whois.GetDidDocument())
+	if err != nil {
+		return nil, sdkerrors.Wrap(types.ErrDidDocumentInvalid, "Failed to unmarshal DID document")
+	}
+
+	// Convert owner and buyer address strings to sdk.AccAddress
+	buyer, _ := sdk.AccAddressFromBech32(msg.Creator)
```
Comment (joshLong145) [inline x/registry/keeper/msg_server_buy_alias.go]: Since the buyer comes from the message body we should first do checks to confirm the Creator can in fact perform this opperation

File: x/registry/keeper/msg_server_transfer_alias.go [hunk 108]
```diff
@@ -0,0 +1,58 @@
...
+
+	// Send Coins to new owner
+	err = k.bankKeeper.SendCoins(ctx, aliasOwner, aliasOwner, sdk.NewCoins(sdk.NewCoin("snr", sdk.NewInt(int64(msg.GetAmount())))))
+	if err != nil {
+		return nil, sdkerrors.Wrapf(err, "failed to send coins to %s", msg.GetRecipient())
+	}
+
+	// Transfer Alias to new owner if transaction is successful
+	msg.Recipient = msg.Creator
+	whois.Alias[idx] = alias
```
Comment (joshLong145) [inline x/registry/keeper/msg_server_transfer_alias.go]: should check the index so that it doesnt cause a panic in edge cases.

File: x/registry/types/message_buy_alias.go [hunk 109]
```diff
@@ -0,0 +1,62 @@
...
+	return nil
+}
+
+func ValidateAlias(name string) error {
+	// Check if Alias length is valid
+	if len(name) < 3 {
+		return sdkerrors.Wrap(ErrAliasUnavailable, "Alias must be at least 3 characters long")
+	}
+	// Check if alias is only alpha-numeric
+	regexp := regexp.MustCompile(`^[a-zA-Z0-9]+$`)
```
Comment (joshLong145) [inline x/registry/types/message_buy_alias.go:75]: we might want to move this regex for snr validation out to a config

**Review by joshLong145 — CHANGES_REQUESTED** [review]

File: internal/highway/http/server.go [hunk 110]
```diff
@@ -50,7 +51,8 @@ type HighwayServer struct {
 	Webauthn *client.WebAuthn
 
 	// Http Properties
-	Router     *gin.Engine
+	Router     *mux.Router
+	Engine     *gin.Engine
```
Comment (mcjcloud) [inline internal/highway/http/server.go]: Reason for this change?

File: x/registry/keeper/msg_server_transfer_alias.go (hunk 87 above)
Comment (mcjcloud) [reply x/registry/keeper/msg_server_transfer_alias.go]: Can you link it in the comment?

File: cmd/motor-lib/wasm.go (hunk 92 above)
Comment (prdlk) [reply cmd/motor-lib/wasm.go]: We dont have p2p interaction methods or highway interaction methods yet

File: internal/highway/http/crud_object_test.go (hunk 93 above)
Comment (prdlk) [reply internal/highway/http/crud_object_test.go]: Done

File: internal/highway/http/crud_registry.go (hunk 94 above)
Comment (prdlk) [reply internal/highway/http/crud_registry.go]: Webauthn methods have been removed. Dedicated site for webauthn is at https://github.com/sonr-io/webauthn-vercel

File: pkg/did/credential.go (hunk 100 above)
Comment (prdlk) [reply pkg/did/credential.go:103]: Required for implementation for Webauthn package - however, new repo has been created to handle this. https://github.com/sonr-io/webauthn-vercel

File: pkg/host/common.go (hunk 101 above)
Comment (prdlk) [reply pkg/host/common.go:52]: Yes for now - out of scope

File: internal/highway/http/crud_ipfs.go (hunk 106 above)
Comment (prdlk) [reply internal/highway/http/crud_ipfs.go]: good catch

File: internal/highway/http/server.go (hunk 110 above)
Comment (prdlk) [reply internal/highway/http/server.go]: Removing router completely as we have separate repo for handling this now https://github.com/sonr-io/webauthn-vercel

Comment (prdlk) [reply internal/highway/http/server.go]: Will change back to original name

File: x/registry/types/message_buy_alias.go (hunk 109 above)
Comment (prdlk) [reply x/registry/types/message_buy_alias.go:75]: Plan is to incorporate as validation method for message type. Will convert the function.

File: cmd/highway-cli/main.go (hunk 4 above)
Comment (joshLong145) [reply cmd/highway-cli/main.go:41]: I think it gives more information on error if the highway doesnt stand up its clearer on the reason

File: cmd/highway-cli/highwaycmd/auth.go (hunk 3 above)
Comment (mcjcloud) [reply cmd/highway-cli/highwaycmd/auth.go]: Fixed.

File: x/registry/keeper/msg_server_transfer_alias.go (hunk 86 above)
Comment (ntindle) [reply x/registry/keeper/msg_server_transfer_alias.go]: #327

File: cmd/sonrd/genaccounts.go (hunk 26 above)
Comment (ntindle) [reply cmd/sonrd/genaccounts.go:33]: Needed?

File: internal/highway/http/crud_bucket.go (hunk 27 above)
Comment (ntindle) [reply internal/highway/http/crud_bucket.go]: done

File: cmd/sonrd/genaccounts.go (hunk 26 above)
Comment (mcjcloud) [reply cmd/sonrd/genaccounts.go:33]: https://github.com/sonr-io/sonr/issues/329

File: internal/highway/x/prometheus/events.go (hunk 39 above)
Comment (mcjcloud) [reply internal/highway/x/prometheus/events.go:24]: Made an issue: #331

**Review by drgomesp — DISMISSED** [review]

**Review by mcjcloud — DISMISSED** [review]

**Review by joshLong145 — DISMISSED** [review]

**Review by mcjcloud — DISMISSED** [review]

**Review by joshLong145 — DISMISSED** [review]

**Comment by ntindle** [comment]
```Error: An error occurred trying to start process '/bin/bash' with working directory '/Users/runner/work/sonr/sonr/cmd/motor-lib'. No such file or directory```

**Review by joshLong145 — APPROVED** [review]

**Review by mcjcloud — APPROVED** [review]
